-- =============================================================
-- Login Module — Database Schema (PostgreSQL)
-- Generated by: Requirement Agent
-- =============================================================

-- User account table for authentication
CREATE TABLE "user" (
    id              SERIAL          PRIMARY KEY,
    email           VARCHAR(255)    NOT NULL UNIQUE,
    password_hash   VARCHAR(255)    NOT NULL,
    first_name      VARCHAR(100)    NOT NULL,
    last_name       VARCHAR(100)    NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Index on email for fast login lookups
CREATE INDEX idx_user_email ON "user" (email);

-- =============================================================
-- Home Page Module — Database Schema (PostgreSQL)
-- Generated by: Requirement Agent
-- =============================================================

-- Product categories
CREATE TABLE category (
    id              SERIAL          PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL UNIQUE,
    description     TEXT,
    image_url       VARCHAR(500),
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Products catalog
CREATE TABLE product (
    id              SERIAL          PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    description     TEXT,
    price           NUMERIC(10, 2)  NOT NULL CHECK (price >= 0),
    image_url       VARCHAR(500),
    category_id     INTEGER         REFERENCES category(id) ON DELETE SET NULL,
    rating          NUMERIC(2, 1)   NOT NULL DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
    review_count    INTEGER         NOT NULL DEFAULT 0 CHECK (review_count >= 0),
    is_featured     BOOLEAN         NOT NULL DEFAULT FALSE,
    is_trending     BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Indexes for product filtering
CREATE INDEX idx_product_category_id ON product (category_id);
CREATE INDEX idx_product_is_featured ON product (is_featured) WHERE is_featured = TRUE;
CREATE INDEX idx_product_is_trending ON product (is_trending) WHERE is_trending = TRUE;
CREATE INDEX idx_product_name ON product USING gin (to_tsvector('english', name));

-- Shopping cart items (per user)
CREATE TABLE cart_item (
    id              SERIAL          PRIMARY KEY,
    user_id         INTEGER         NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    product_id      INTEGER         NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    quantity        INTEGER         NOT NULL DEFAULT 1 CHECK (quantity >= 1),
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, product_id)
);

CREATE INDEX idx_cart_item_user_id ON cart_item (user_id);

-- Product reviews
CREATE TABLE review (
    id              SERIAL          PRIMARY KEY,
    user_id         INTEGER         NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    product_id      INTEGER         NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    rating          INTEGER         NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment         TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, product_id)
);

CREATE INDEX idx_review_product_id ON review (product_id);

-- Newsletter subscribers
CREATE TABLE newsletter_subscriber (
    id              SERIAL          PRIMARY KEY,
    email           VARCHAR(255)    NOT NULL UNIQUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_newsletter_subscriber_email ON newsletter_subscriber (email);

-- =============================================================
-- Hero Banner Module — Database Schema (PostgreSQL)
-- Generated by: Requirement Agent
-- =============================================================

-- Hero banner content for the home page
CREATE TABLE hero_banner (
    id              SERIAL          PRIMARY KEY,
    title           VARCHAR(255)    NOT NULL,
    subtitle        TEXT,
    image_url       VARCHAR(500)    NOT NULL,
    cta_text        VARCHAR(100)    NOT NULL DEFAULT 'Shop Now',
    cta_link        VARCHAR(500)    NOT NULL DEFAULT '/shop',
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Index for quickly fetching the active banner
CREATE INDEX idx_hero_banner_is_active ON hero_banner (is_active, created_at DESC) WHERE is_active = TRUE;

-- =============================================================
-- Sitemap Page: No database changes required (frontend-only feature)
-- =============================================================
